### ISSUE TITLE
What is fulfilment update LMS?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#19]
Input work stream Finance & Admin:
- Stream: We think is is a service that passes the order confirmation through to the LMS. Is That correct?

**Comment by cliftonc** [comment]
Yes, this is the intention.

- Information is passed from the Marketplace to the LMS to allow the LMS to display material that has been selected (purchased or selected for future purchase) to a teacher or learner.
- This represents half of the 'fulfilment' from a digital perspective, with the other half being the same message sent to the LP to allow it to ensure that access will be granted when a user arrives at a future point.

Some open items that will be explored in the technical track:

- Does this fulfilment contain the final link to the end product?  Or is that provided by the update that comes to the LMS from the LP?  (the latter may be more robust as the LP is then responsible for ensuring the link is correct)

**Comment by MarcelUntied** [comment]
I think the update from the market place should be translated in a list of products that are confirmed by the user (teacher/pupil/student). So the LMS knows which products will be available to the user. The update from the Learning Application should be the link to the real product. The update from the Learning Application is the 'real' delivery in my opinion

**Comment by wvholland** [comment]
> I think the update from the market place should be translated in a list of products that are confirmed by the user (teacher/pupil/student). So the LMS knows which products will be available to the user. The update from the Learning Application should be the link to the real product. The update from the Learning Application is the 'real' delivery in my opinion

Very good discussion that we need to understand by heart. Clifton (from content delivery perspective) and me (from distributer/LMS perspective) have spend several hours/beers on this point together with Albert fromTLN. According to the Dutch situation - with tenders on learnng materials for Secondary Education the distributer takes the responsibility to fulfill the learning materials. Technically it's always - at the end - the LA that provides this fulfillment and the MP can 'jump high and low' to get this arranged but the LA need to provide. Therefor we came to an understanding with the triangel where the moment the entitlement is settled on the LML (LeermiddelenLijst) the MP (or sales agent) provides that information to the LMS (or multiple) (so that they can show the purchased or (allowed) selected materials as tiles (links) in the LMS (read the MP has delivered ... functionally), the MP also informs the LA's to inform them "be prepared, these materials will be used in the future for this number of people for these school, vak, klas, etc). As the LA can technically fulfill (read deliver) it will inform the LMS "I'm ready all is settled" (might be last minute change in URL or whatever). As we all deliver transparent info (MP, LMS, LP) then we would hope to see (more or less) similar figures here ...

**Comment by benkoers** [comment]
Also from a schoolsperspective (we discussed it in track 2) the LMC / ICT-coordinator wants to 'check' if everything is delivered by the sales-agent. So from the sales-agent perspective it is a kind of an confirmation that everything is delivered (in the LMS of the school) . The next step is what Winfried described:  is it accessible and does it work (provided by the LA). **For me the question is: is the fulfillment in the LMS **after** the creation of entitlement of is a separated step?**

**Comment by MarcelUntied** [comment]
@benkoers Good question!

**Comment by wvholland** [comment]
Can we rephrase the question as it is now not clear for me. something like:
**Is the fulfillment of the LML in the LMS done after the establishment of entitlement or is it a seperate step?**

see on entitlement also [here ](https://github.com/stichtingsem/functional-overview/issues/10#issuecomment-646478462)

**Comment by HJTLN** [comment]
Can a reference to which use case(step) this (and other) question or issue is related be added in tags or description? This makes it possible to backtrack the context without reading all the posts (e.g. OA3.4 or UC3 step 4)

**Comment by edwinverwoerd** [comment]
> Is the fulfillment of the LML in the LMS done after the establishment of entitlement or is it a seperate step?
 This should be two separate steps. If LML has been established between school and sales agent, this information can be used for setting up the pre-condition of the LMS. Entitlements do not go to an LA until the end user has asked for confirmation, or when the school can only supply the correct numbers in time, given the time. AND since the LA returns a signal from receive and "ready" to both LMS and MP, separating these information streams is no problem

**Comment by MarcelUntied** [comment]
https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
