### ISSUE TITLE
Are service credits still necessary?

### ISSUE THREAD

**Issue by MarcelUntied** [stichtingsem/functional-overview#9]
Input Work Stream Finance & Admin:
- In the current chain service credits provide access to pupils (secondary education) when there are delivery issues
- Determine minimal requirements for access to a license (functional)
- If necessary > Service credits are OK if they are traceable to a school and Sales Agent

**Comment by benkoers** [comment]
we discussed this also in track 2 and took the starting point:  the ecosystem does not need service-credits/licenses. The questions is: is that due-able from a track 3 point of view

**Comment by MarcelUntied** [comment]
@benkoers I think the track leads should discuss this point before bringing it back to the streams. @eliashassing154 Can you put it on the agenda for our first stream lead meeting?

**Comment by eliashassing154** [comment]
@MarcelUntied noted

**Comment by eliashassing154** [comment]
@benkoers @MarcelUntied @cliftonc one of the design principles however, is that they are possible but more importantly not necessary. It is possible at any time to the flow LML to usage. Since another principle is that the SIS has correct and up to date information, changes will be shared and available to all services at any time. So should you require more licences than initially purchased, you can "order" by starting to use them. The LA should flag that, notify the other services and the Marketplace should then bill the school.  There's a couple of things we probably need to define more clearly

**Comment by HJTLN** [comment]
Is this within scope for the two use cases at hand?

**Comment by MarcelUntied** [comment]
@HJTLN We discussed this issue in the stream lead meeting. If entitlement is traceable to school and sales agent the service credit would be unnecessary. This is input to the development of the solution/proof of concept

**Comment by edwinverwoerd** [comment]
So the end conclusion is NO service credit needed

**Comment by MarcelUntied** [comment]
In the work stream finance & administration we discussed this issue. We think service credits will be unecessary because of the introduction of the entitlement. We think this issue can be closed.

@eliashassing154 @cliftonc Do you agree?

**Comment by cliftonc** [comment]
Yes, I agree.  I think it should be framed that we design the solution in a way that they will be unnecessary, but let's make sure we do that check at the end to confirm we have achieved that.

**Comment by eliashassing154** [comment]
Jep, agreed.

**Comment by eliashassing154** [comment]
@MarcelUntied can we close this issue for now?

**Comment by MarcelUntied** [comment]
@eliashassing154 Ok!

https://github.com/stichtingsem/functional-overview/blob/master/proposed-decisions.md
